# Generated by Django 4.0 on 2022-08-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate', '0004_review_alter_watchlist_stream_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='ratings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='watchmate.review'),
            preserve_default=False,
        ),
    ]
