# Generated by Django 4.0 on 2022-08-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('watchmate', '0006_remove_streamplatform_ratings_review_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
